// Soft Archive direction: warm cream canvas, editorial lead cards, DM Serif Display + Manrope, restrained motion.
import { useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import { Link, useLocation } from "wouter";
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, BellRing, BrainCircuit, CalendarDays, Check, ChevronRight, CircleAlert, CircleCheck, FileText, Filter, Headphones, Laptop, Lightbulb, LockKeyhole, MoreHorizontal, Package, Plus, Receipt, ReceiptText, RefreshCcw, Search, ShieldCheck, Smartphone, Sparkles, Upload, Watch, Wrench } from "lucide-react";
import { AppShell } from "@/components/stashly/AppShell";
import { Brand } from "@/components/stashly/Brand";
import { ChevronLink, MiniMetric, PlaceholderPage, ProductCard, SectionHeading, StatusBadge } from "@/components/stashly/Primitives";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { AccountGate, ConnectedAskStashVaultPage, ConnectedBeforeYouBuyPage, ConnectedDashboard, ConnectedDocumentsPage, ConnectedProductDetails, ConnectedRepairPage, ConnectedSettingsPage, ConnectedStashPage, ConnectedUploadPage, ManualProductPage, ReceiptReviewPage, ReceiptScanPage } from "@/components/stashly/ConnectedViews";

const heroImage = "/manus-storage/stashly-hero_1fdf37be.jpg";
const productImage = "/manus-storage/stashly-product-vignette_7760bc1c.jpg";

function Dashboard() {
  return <div className="page page--dashboard">
    <div className="page-topbar"><div><span className="eyebrow">Wednesday, 14 August 2026</span><h1>Good morning, Alex<span className="heading-period">.</span></h1></div><div className="page-topbar__actions"><button className="icon-button topbar-bell" aria-label="Notifications"><Bell size={18} /><span /></button><Link href="/add" className="button button--primary"><Plus size={17} /> Add to stash</Link></div></div>
    <section className="dashboard-hero">
      <div className="hero-card" style={{ "--hero-image": `url(${heroImage})` } as CSSProperties}><div className="hero-card__copy"><span className="eyebrow eyebrow--light">Your ownership, at a glance</span><h2>Keep the good<br /><em>details</em> close.</h2><p>Stashly helps you remember what you bought, when it needs care, and what to do next.</p><Link href="/stash" className="text-link text-link--light">View your full stash <ArrowUpRight size={15} /></Link></div><div className="hero-card__stamp"><span>ST</span><small>01 / 04</small></div></div>
      <div className="capture-card"><div className="capture-card__top"><span className="archive-tab archive-tab--blush">NEW RITUAL</span><MoreHorizontal size={19} /></div><div className="receipt-icon"><Receipt size={27} strokeWidth={1.5} /></div><span className="eyebrow">Save a detail</span><h3>Have a new receipt?</h3><p>Upload it once. Stashly will keep the dates, documents, and next steps together.</p><Link href="/upload" className="button button--dark button--small">Upload a receipt <Upload size={15} /></Link><span className="capture-card__note"><Sparkles size={13} /> AI understanding arrives in Phase 2</span></div>
    </section>
    <section className="metric-row" aria-label="Stash overview"><MiniMetric label="Items in your stash" value="12" note="+2 this month" tone="blush" /><MiniMetric label="Protected by warranty" value="08" note="67% of your stash" tone="sage" /><MiniMetric label="Needs your eye" value="03" note="One return window soon" tone="lavender" /></section>
    <div className="dashboard-grid">
      <section className="panel panel--stash"><SectionHeading eyebrow="The things you keep" title="A little order, already." action={<ChevronLink href="/stash">See all 12 items</ChevronLink>} /><div className="product-grid"><ProductCard kind="laptop" tone="sage" name="MacBook Air" detail="Bought 12 Mar 2025" status="safe" statusText="Warranty · 214 days" /><ProductCard kind="headphones" tone="blush" name="QuietComfort 45" detail="Bought 08 Jan 2025" status="watch" statusText="Return · 9 days" /><ProductCard kind="camera" tone="lavender" name="Fujifilm X-T30 II" detail="Bought 22 Nov 2024" status="safe" statusText="Warranty · 81 days" /></div><div className="panel-footnote"><span className="dot dot--sage" /> Last updated just now <span className="footnote-divider" /><Link href="/add">Add another item <Plus size={14} /></Link></div></section>
      <section className="panel panel--attention"><SectionHeading eyebrow="A gentle nudge" title="Worth a look" /><div className="attention-list"><Link href="/product/2" className="attention-item"><span className="attention-item__icon attention-item__icon--peach"><CalendarDays size={17} /></span><span><strong>Your headphone return window</strong><small>Closes in 9 days · Bose QC45</small></span><ChevronRight size={16} /></Link><Link href="/documents" className="attention-item"><span className="attention-item__icon attention-item__icon--sage"><FileText size={17} /></span><span><strong>One receipt still needs a home</strong><small>Uploaded 2 days ago · Kitchen</small></span><ChevronRight size={16} /></Link><Link href="/risk-radar" className="attention-item"><span className="attention-item__icon attention-item__icon--lavender"><ShieldCheck size={17} /></span><span><strong>Warranty details are looking good</strong><small>8 of 12 items are covered</small></span><ChevronRight size={16} /></Link></div></section>
    </div>
    <section className="insight-strip"><div className="insight-strip__icon"><img className="insight-strip__mark" src="/manus-storage/stashly-mark_6b22b5b6.png" alt="" /></div><div><span className="eyebrow">A small thought from Stashly</span><p>“The best time to save a warranty is before you need it.”</p></div><Link href="/ask-stashly" className="text-link">Ask Stashly <ArrowUpRight size={15} /></Link></section>
    <section className="rhythm-section"><SectionHeading eyebrow="Your ownership rhythm" title="From purchase to peace of mind." action={<span className="quiet-label">A glimpse of what’s ahead</span>} /><div className="rhythm-track"><div className="rhythm-step rhythm-step--done"><span className="rhythm-step__number"><Check size={15} /></span><span><strong>Buy</strong><small>Something worth keeping</small></span></div><div className="rhythm-line rhythm-line--done" /><div className="rhythm-step rhythm-step--done"><span className="rhythm-step__number"><Check size={15} /></span><span><strong>Remember</strong><small>Receipt, dates, details</small></span></div><div className="rhythm-line" /><div className="rhythm-step"><span className="rhythm-step__number">03</span><span><strong>Protect</strong><small>Warranties & returns</small></span></div><div className="rhythm-line" /><div className="rhythm-step"><span className="rhythm-step__number">04</span><span><strong>Act</strong><small>When something changes</small></span></div></div></section>
  </div>;
}

function StashPage() {
  const items = [
    ["laptop", "sage", "MacBook Air", "Electronics · Bought 12 Mar 2025", "safe", "Warranty · 214 days"],
    ["headphones", "blush", "QuietComfort 45", "Electronics · Bought 08 Jan 2025", "watch", "Return · 9 days"],
    ["camera", "lavender", "Fujifilm X-T30 II", "Electronics · Bought 22 Nov 2024", "safe", "Warranty · 81 days"],
    ["phone", "sand", "iPhone 15 Pro", "Electronics · Bought 16 Sep 2024", "safe", "Warranty · 19 days"],
    ["package", "blush", "Air purifier", "Home · Bought 02 Jul 2024", "expired", "Warranty expired"],
    ["package", "sage", "Standing desk", "Home · Bought 18 May 2024", "safe", "Warranty · 40 days"],
  ] as const;
  return <div className="page"><div className="page-topbar"><div><span className="eyebrow">Your archive · 12 items</span><h1>My Stash<span className="heading-period">.</span></h1></div><Link href="/add" className="button button--primary"><Plus size={17} /> Add to stash</Link></div><div className="toolbar"><div className="search-field"><Search size={16} /><input placeholder="Search your stash" aria-label="Search your stash" /></div><button className="toolbar-button"><Filter size={16} /> All categories</button><button className="toolbar-button"><ArrowDownRight size={16} /> Newest first</button></div><section className="stash-catalog">{items.map(([kind, tone, name, detail, status, statusText]) => <ProductCard key={name} kind={kind} tone={tone} name={name} detail={detail} status={status} statusText={statusText} />)}</section></div>;
}

function ProductDetailsPage() {
  return <div className="page"><div className="back-link"><Link href="/stash"><ChevronRight size={15} className="back-link__icon" /> Back to My Stash</Link></div><div className="detail-layout"><section className="product-detail-card"><div className="product-detail-card__art" style={{ backgroundImage: `url(${productImage})` }}><span className="archive-tab archive-tab--sage">ELECTRONICS</span></div><div className="product-detail-card__copy"><span className="eyebrow">Saved 12 March 2025</span><h1>MacBook Air<span className="heading-period">.</span></h1><p className="product-subtitle">13-inch · Midnight · M3 chip</p><div className="detail-status"><StatusBadge status="safe">Warranty active</StatusBadge><span>214 days remaining</span></div></div></section><aside className="detail-sidebar"><section className="panel"><SectionHeading eyebrow="Keep the paper trail" title="Documents" action={<Link href="/documents" className="icon-button"><ArrowUpRight size={16} /></Link>} /><div className="document-row"><span className="document-row__icon"><Receipt size={16} /></span><span><strong>Apple Store receipt</strong><small>PDF · 12 March 2025</small></span><MoreHorizontal size={17} /></div><div className="document-row"><span className="document-row__icon"><ShieldCheck size={16} /></span><span><strong>Limited warranty</strong><small>Saved from receipt</small></span><MoreHorizontal size={17} /></div></section><section className="panel panel--soft"><span className="eyebrow">Next useful thing</span><h3>Keep the serial number nearby.</h3><p>It can make support, repairs, and returns much easier.</p><Link href="/ask-stashly" className="text-link">Ask Stashly for help <ArrowUpRight size={15} /></Link></section></aside></div></div>;
}

function AddPage() {
  return <div className="page"><div className="page-topbar"><div><span className="eyebrow">Add to your archive</span><h1>Keep something close<span className="heading-period">.</span></h1></div></div><div className="add-choice-grid"><Link href="/scan" className="add-choice add-choice--blush"><span className="add-choice__icon"><Upload size={26} /></span><span className="eyebrow">The easy way</span><h2>Read a receipt</h2><p>Stashly brings forward only the details it can read. You review every field before saving.</p><span className="text-link">Choose a receipt <ArrowUpRight size={15} /></span></Link><Link href="/add/manual" className="add-choice add-choice--sage"><span className="add-choice__icon"><Plus size={26} /></span><span className="eyebrow">Take your time</span><h2>Add details yourself</h2><p>Start a clean product record and fill in the essentials at your own pace.</p><span className="text-link">Start a record <ArrowUpRight size={15} /></span></Link></div><div className="add-note"><Sparkles size={16} /><span>Every receipt stays private, and nothing is saved to your stash until you’ve reviewed it.</span></div></div>;
}

function UploadPage() {
  return <div className="page"><div className="back-link"><Link href="/add"><ChevronRight size={15} className="back-link__icon" /> Back to add</Link></div><div className="upload-layout"><section><span className="eyebrow">Receipt inbox</span><h1>One small upload.<br /><em>A lot less to remember.</em></h1><p className="lede">Drop a receipt here and Stashly will be ready to understand it when the next phase opens.</p></section><div className="upload-dropzone"><div className="upload-dropzone__icon"><Upload size={25} /></div><h2>Choose a receipt to begin</h2><p>PDF, JPG, or PNG · up to 10 MB</p><button className="button button--dark">Choose a file <ArrowUpRight size={16} /></button><span className="upload-dropzone__note"><ShieldCheck size={14} /> Your documents stay private to your archive.</span></div></div></div>;
}

function RiskRadarPage() {
  return <div className="page"><div className="page-topbar"><div><span className="eyebrow">Care & coverage</span><h1>Risk Radar<span className="heading-period">.</span></h1></div><div className="radar-score"><span>Overall coverage</span><strong>82<small>/100</small></strong><span className="radar-score__trend"><ArrowUpRight size={14} /> 6 pts this month</span></div></div><div className="risk-grid"><section className="panel risk-overview"><SectionHeading eyebrow="A quiet overview" title="Most of your stash is in good shape." /><div className="risk-ring"><div><strong>82</strong><span>covered</span></div></div><div className="risk-legend"><span><i className="legend-dot legend-dot--sage" /> Warranty active <b>8</b></span><span><i className="legend-dot legend-dot--peach" /> Needs attention <b>3</b></span><span><i className="legend-dot legend-dot--lavender" /> No details yet <b>1</b></span></div></section><section className="panel"><SectionHeading eyebrow="Needs your eye" title="A few open loops" /><div className="risk-list"><div><span className="attention-item__icon attention-item__icon--peach"><CalendarDays size={17} /></span><p><strong>Return window</strong><small>QuietComfort 45 · 9 days left</small></p><StatusBadge status="watch">Soon</StatusBadge></div><div><span className="attention-item__icon attention-item__icon--lavender"><CircleAlert size={17} /></span><p><strong>Warranty details</strong><small>Air purifier · expired 21 days ago</small></p><StatusBadge status="expired">Review</StatusBadge></div><div><span className="attention-item__icon attention-item__icon--sage"><Check size={17} /></span><p><strong>Everything else</strong><small>Up to date and accounted for</small></p><StatusBadge status="safe">Good</StatusBadge></div></div></section></div></div>;
}

function DocumentsPage() {
  const docs = [["Apple Store receipt", "MacBook Air", "12 Mar 2025"], ["Bose receipt", "QuietComfort 45", "08 Jan 2025"], ["Warranty card", "Fujifilm X-T30 II", "22 Nov 2024"], ["Order confirmation", "iPhone 15 Pro", "16 Sep 2024"]];
  return <div className="page"><div className="page-topbar"><div><span className="eyebrow">Your paper trail</span><h1>Documents<span className="heading-period">.</span></h1></div><Link href="/upload" className="button button--primary"><Upload size={17} /> Upload receipt</Link></div><div className="document-summary"><MiniMetric label="Saved documents" value="18" note="Across 12 items" tone="blush" /><MiniMetric label="Receipts" value="12" note="One per item" tone="sage" /><MiniMetric label="Needs sorting" value="01" note="Uploaded recently" tone="lavender" /></div><section className="panel documents-panel"><SectionHeading eyebrow="All your records" title="Nothing lost in the drawer." action={<button className="toolbar-button"><Filter size={16} /> Filter</button>} /><div className="document-table"><div className="document-table__head"><span>Document</span><span>Item</span><span>Added</span><span /></div>{docs.map(([doc, item, date]) => <div className="document-table__row" key={doc}><span className="document-table__name"><span className="document-row__icon"><FileText size={16} /></span><strong>{doc}</strong></span><span>{item}</span><span>{date}</span><MoreHorizontal size={17} /></div>)}</div></section></div>;
}

function LandingDashboardMockup() {
  const productCards = [
    { name: "MacBook Air", meta: "Bought 12 Mar 2025", tone: "sage", status: "Warranty active", icon: Laptop },
    { name: "QuietComfort 45", meta: "Bought 08 Jan 2025", tone: "peach", status: "Return ends soon", icon: Headphones },
    { name: "iPhone 15 Pro", meta: "Bought 16 Sep 2024", tone: "lavender", status: "Warranty active", icon: Smartphone },
    { name: "AquaWash 7kg", meta: "Bought 02 Jul 2024", tone: "rose", status: "Expires soon", icon: Package },
    { name: "Pixel Watch", meta: "Bought 18 May 2024", tone: "sand", status: "Warranty active", icon: Watch },
  ] as const;
  return <div className="landing-dashboard-mockup" aria-label="Illustrated Stashly dashboard showing products and protection status"><div className="landing-dashboard-mockup__top"><span className="landing-window-dots"><i /><i /><i /></span><span className="landing-window-title">Your ownership, at a glance</span><span className="landing-window-spark"><Sparkles size={13} /></span></div><div className="landing-dashboard-mockup__body"><div className="landing-dashboard-intro"><span className="eyebrow">My Stash · 12 items</span><strong>A little order,<br />already.</strong><span className="landing-dashboard-intro__line" /></div><div className="landing-product-grid">{productCards.map(({ name, meta, tone, status, icon: Icon }) => <div className={`landing-product-card landing-product-card--${tone}`} key={name}><div className="landing-product-card__icon"><Icon size={17} strokeWidth={1.7} /></div><span className="landing-product-card__arrow"><ArrowUpRight size={12} /></span><strong>{name}</strong><small>{meta}</small><span className="landing-product-card__status"><i />{status}</span></div>)}</div></div><div className="landing-dashboard-mockup__footer"><span><CircleCheck size={13} /> All details in one place</span><span>Updated just now · <b>ST</b></span></div></div>;
}

function LandingPage() {
  return <div className="landing-page">
    <header className="landing-header"><Brand compact /><nav className="landing-nav" aria-label="Landing navigation"><a href="#how-it-works">How it works</a><a href="#why-stashly">Why Stashly</a><a href="#something-wrong">Something’s wrong?</a></nav><div className="landing-header__actions"><Link href="/login" className="landing-login-link">Sign in</Link><Link href="/signup" className="button button--primary button--small">Start your stash <ArrowUpRight size={14} /></Link></div></header>
    <main>
      <section className="landing-hero"><div className="landing-hero__copy"><span className="eyebrow">The personal ownership assistant</span><h1>Everything you own.<br /><em>Remembered.</em></h1><p>Stashly keeps your receipts, warranties, return windows and product history in one intelligent place — and helps you take action when something goes wrong.</p><div className="landing-hero__actions"><Link href="/signup" className="button button--primary">Start Your Stash <ArrowUpRight size={16} /></Link><a href="#how-it-works" className="button button--quiet">See How It Works <ArrowDown size={16} /></a></div><div className="landing-hero__trust"><span className="landing-hero__avatars"><i>AM</i><i>JR</i><i>SK</i></span><span>Made for the things<br />you want to keep useful.</span></div></div><div className="landing-hero__visual"><span className="landing-hero__note landing-hero__note--one">Receipts, dates,<br />details.</span><span className="landing-hero__note landing-hero__note--two"><Sparkles size={13} /> It remembers.</span><LandingDashboardMockup /></div></section>
      <section className="landing-marquee" aria-label="Stashly benefits"><span>RECEIPTS</span><i /> <span>WARRANTIES</span><i /> <span>RETURN WINDOWS</span><i /> <span>PRODUCT HISTORY</span><i /> <span>SMART REMINDERS</span></section>
      <section className="landing-section landing-section--process" id="how-it-works"><div className="landing-section__heading"><span className="eyebrow">How it works</span><h2>One small ritual.<br /><em>A lot less to remember.</em></h2><p>Stashly turns the paper trail of everyday life into a calm, useful record you can act on.</p></div><div className="landing-process-grid"><div className="landing-process-card landing-process-card--lead"><span className="landing-process-card__number">01</span><div className="landing-process-card__icon"><Upload size={21} /></div><h3>Upload</h3><p>Save a receipt, warranty card, or order confirmation in a single place.</p><span className="landing-process-card__scribble">Keep the paper trail.</span></div><div className="landing-process-card"><span className="landing-process-card__number">02</span><div className="landing-process-card__icon"><BrainCircuit size={21} /></div><h3>AI understands</h3><p>Important details become clear: what you bought, when, and from whom.</p></div><div className="landing-process-card"><span className="landing-process-card__number">03</span><div className="landing-process-card__icon"><ArchiveIcon /></div><h3>Stashly remembers</h3><p>Your products, documents, and dates stay connected as one living record.</p></div><div className="landing-process-card"><span className="landing-process-card__number">04</span><div className="landing-process-card__icon"><ShieldCheck size={21} /></div><h3>You stay protected</h3><p>Get the right reminder and the next useful step before a window closes.</p></div></div></section>
      <section className="landing-section landing-section--problem" id="why-stashly"><div className="landing-problem__copy"><span className="eyebrow">The after part</span><h2>We remember buying things.<br /><em>We forget everything that comes after.</em></h2><p>Invoices get lost in inboxes. Warranties quietly expire. Return windows close while products sit in a drawer. Stashly gives the details a home before they become a problem.</p><Link href="/signup" className="text-link">Give your details a home <ArrowRight size={15} /></Link></div><div className="landing-problem-grid"><div className="landing-problem-card landing-problem-card--rose"><ReceiptText size={20} /><strong>Invoice lost</strong><span>Somewhere in an email thread.</span></div><div className="landing-problem-card landing-problem-card--sand"><LockKeyhole size={20} /><strong>Warranty forgotten</strong><span>Until the day you need it.</span></div><div className="landing-problem-card landing-problem-card--peach"><CalendarDays size={20} /><strong>Return window missed</strong><span>Just a few days too late.</span></div><div className="landing-problem-card landing-problem-card--lavender"><RefreshCcw size={20} /><strong>Service details scattered</strong><span>Across notes, receipts, and tabs.</span></div></div></section>
      <section className="landing-section landing-section--solution"><div className="landing-solution__heading"><span className="eyebrow">The Stashly way</span><h2>From receipt<br /><em>to ready.</em></h2></div><div className="landing-solution-flow"><div className="landing-solution-step landing-solution-step--active"><span className="landing-solution-step__icon"><Receipt size={19} /></span><span><b>Receipt</b><small>Save it once.</small></span></div><div className="landing-solution-arrow"><ArrowDown size={17} /></div><div className="landing-solution-step"><span className="landing-solution-step__icon"><BrainCircuit size={19} /></span><span><b>AI extraction</b><small>Useful bits, made clear.</small></span></div><div className="landing-solution-arrow"><ArrowDown size={17} /></div><div className="landing-solution-step"><span className="landing-solution-step__icon"><ArchiveIcon /></span><span><b>Product saved</b><small>One connected record.</small></span></div><div className="landing-solution-arrow"><ArrowDown size={17} /></div><div className="landing-solution-step"><span className="landing-solution-step__icon"><BellRing size={19} /></span><span><b>Smart reminders</b><small>Before it matters.</small></span></div><div className="landing-solution-arrow"><ArrowDown size={17} /></div><div className="landing-solution-step landing-solution-step--last"><span className="landing-solution-step__icon"><Wrench size={19} /></span><span><b>Action</b><small>When something goes wrong.</small></span></div></div></section>
      <section className="landing-section landing-section--signature" id="something-wrong"><div className="signature-card"><div className="signature-card__label"><span className="eyebrow">A little intelligence, at the right time</span><span className="signature-card__spark"><Sparkles size={14} /></span></div><h2>“Something’s wrong?”</h2><p>My headphones stopped working.</p><div className="signature-product"><span className="signature-product__icon"><Headphones size={23} /></span><span><b>QuietComfort 45</b><small>Saved 08 January 2025</small></span><span className="status-badge status-badge--safe">You're covered.</span></div><div className="signature-checks"><span><Check size={13} /> Warranty active</span><span><Check size={13} /> Invoice found</span><span><Check size={13} /> Product details</span></div><Link href="/ask-stashly" className="button button--dark">Generate Service Request <ArrowUpRight size={16} /></Link></div><div className="signature-copy"><span className="eyebrow">When something goes wrong</span><h3>Less searching.<br /><em>More knowing what to do.</em></h3><p>Stashly checks the ownership information you already saved and brings the useful answer forward.</p><div className="signature-copy__line"><span className="signature-copy__dot" /><span>Ownership details<br /><b>ready when you need them.</b></span></div></div></section>
      <section className="landing-section landing-section--sustainability"><div className="sustainability-art"><div className="sustainability-art__circle"><Wrench size={29} /></div><span className="sustainability-art__leaf sustainability-art__leaf--one" /><span className="sustainability-art__leaf sustainability-art__leaf--two" /><span className="sustainability-art__label">MAKE IT LAST</span></div><div className="sustainability-copy"><span className="eyebrow">Care before replace</span><h2>Repair before<br /><em>replace.</em></h2><p>If something breaks, Stashly helps you understand whether it can be repaired or claimed under warranty before you replace it.</p><Link href="/repair" className="text-link">Explore the care path <ArrowRight size={15} /></Link></div></section>
      <section className="landing-cta"><div><span className="eyebrow eyebrow--light">A calmer ownership ritual</span><h2>Keep the good<br /><em>details close.</em></h2></div><Link href="/signup" className="button button--light">Start Your Stash <ArrowUpRight size={16} /></Link></section>
    </main><footer className="landing-footer"><Brand compact /><span>Everything you own. Remembered.</span><span>© 2026 Stashly</span></footer>
  </div>;
}

function ArchiveIcon() {
  return <span className="archive-icon" aria-hidden="true"><span /></span>;
}

function AuthPage({ mode }: { mode: "login" | "signup" }) {
  const { isAuthenticated, user, loading } = useAuth();
  return <div className="auth-page"><div className="auth-aside"><Brand /><div className="auth-aside__copy"><span className="eyebrow">A calmer way to keep what you own in view</span><h1>Everything you own.<br /><em>Remembered.</em></h1><p>Stashly keeps the useful details close, so your things can keep doing their thing.</p><div className="auth-aside__quote"><span>“</span><p>The best time to save a warranty is before you need it.</p></div></div><span className="auth-aside__foot">Stashly · Personal ownership assistant</span></div><main className="auth-card-wrap"><div className="auth-card"><Link href="/" className="auth-back"><ChevronRight size={15} className="back-link__icon" /> Back to home</Link><span className="eyebrow">{mode === "login" ? "Welcome back" : "Start your archive"}</span><h2>{isAuthenticated ? `Welcome${user?.name ? `, ${user.name}` : ""}.` : mode === "login" ? "Good to see you." : "Make room for less remembering."}</h2><p>{isAuthenticated ? "Your personal archive is ready where you left it." : "Sign in securely to keep your products, documents, warranties, and ownership history private to you."}</p>{isAuthenticated ? <Link href="/dashboard" className="button button--dark button--full">Open your stash <ArrowUpRight size={16} /></Link> : <button className="button button--dark button--full" disabled={loading} onClick={() => startLogin()}>{loading ? "Checking your archive…" : "Continue securely"}<ArrowUpRight size={16} /></button>}<div className="auth-switch">{mode === "login" ? <>New to Stashly? <Link href="/signup">Create an archive</Link></> : <>Already have an archive? <Link href="/login">Sign in</Link></>}</div><span className="auth-note"><ShieldCheck size={14} /> Your sign-in uses the secure Manus account system.</span></div></main></div>;
}

function AppPage() {
  const [location] = useLocation();
  if (location === "/") return <LandingPage />;
  if (location === "/login") return <AuthPage mode="login" />;
  if (location === "/signup") return <AuthPage mode="signup" />;
  let content: ReactNode;
  if (location === "/dashboard") content = <ConnectedDashboard />;
  else if (location === "/stash") content = <ConnectedStashPage />;
  else if (location.startsWith("/product/")) { const id = Number(location.split("/").pop()); content = Number.isInteger(id) && id > 0 ? <ConnectedProductDetails productId={id} /> : <div className="page"><PlaceholderPage eyebrow="Your archive" title="We couldn't find this product." description="The record may have been removed, or the link may not be complete." kind="archive" cta={{ label: "Back to stash", href: "/stash" }} /></div>; }
  else if (location === "/add") content = <AddPage />;
  else if (location === "/add/manual") content = <ManualProductPage />;
  else if (location === "/scan") content = <ReceiptScanPage />;
  else if (location.startsWith("/receipt/") && location.endsWith("/review")) { const id = Number(location.split("/")[2]); content = Number.isInteger(id) && id > 0 ? <ReceiptReviewPage documentId={id} /> : <div className="page"><PlaceholderPage eyebrow="Receipt review" title="We couldn't find that review." description="The receipt may have been removed, or the link is incomplete." kind="archive" cta={{ label: "Start with a receipt", href: "/scan" }} /></div>; }
  else if (location === "/upload") content = <ConnectedUploadPage />;
  else if (location === "/risk-radar") content = <RiskRadarPage />;
  else if (location === "/documents") content = <ConnectedDocumentsPage />;
  else if (location === "/ask-stashly") content = <ConnectedAskStashVaultPage />;
  else if (location === "/before-you-buy") content = <ConnectedBeforeYouBuyPage />;
  else if (location === "/repair") content = <ConnectedRepairPage />;
  else if (location === "/settings") content = <ConnectedSettingsPage />;
  else content = <div className="page"><PlaceholderPage eyebrow="Your archive" title="We couldn't find that page." description="The link may be incomplete, or the page may have moved." kind="archive" cta={{ label: "Back to your dashboard", href: "/dashboard" }} /></div>;
  return <AppShell><AccountGate>{content}</AccountGate></AppShell>;
}

export default function Home() {
  return <AppPage />;
}
